// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class CrossyChicken
{
        public const string achievement_got_hit_by_a_car = "CgkIyp6nm4kREAIQAg"; // <GPGSID>
        public const string achievement_supportive = "CgkIyp6nm4kREAIQBQ"; // <GPGSID>
        public const string achievement_out_of_sight = "CgkIyp6nm4kREAIQAw"; // <GPGSID>
        public const string leaderboard_hi_score = "CgkIyp6nm4kREAIQBg"; // <GPGSID>
        public const string achievement_started_the_game = "CgkIyp6nm4kREAIQAQ"; // <GPGSID>
        public const string achievement_persistent = "CgkIyp6nm4kREAIQBA"; // <GPGSID>

}

